### ISSUE TITLE
[Return] is deprecated, implement RETURN as language keyword

### ISSUE THREAD

**Issue by David-Lannion** [jnhyperion/HyperRobotFrameworkPlugin#12]
New RETURN statement adds a uniform way to return from user keywords. It can be used for returning values when the keyword has been executed like when using the old [Return] setting, and also for returning prematurely like the old Return From Keyword keyword supports.

The old [Return] setting and old keywords Return From Keyword and Return From Keyword If continue to work. The plan is to deprecate and remove them in the future.

See : https://github.com/robotframework/robotframework/blob/master/doc/releasenotes/rf-5.0rc2.rst#return

**Comment by jnhyperion** [comment]
thanks for your feedback, will consider adding this feature in next release.

**Comment by jnhyperion** [comment]
Implemented in version 0.0.9
