### ISSUE TITLE
initializing a Library using WITH NAME abc fail to autocomplete keywords

### ISSUE THREAD

**Issue by alexshagiev** [jnhyperion/HyperRobotFrameworkPlugin#14]
If i have a library called RobotLibIsBest and i init it as follows:

*** Settings ***
Library        RobotLibIsBest

Then the keywords autocomplete in intellij with pycharm plugin with out any problems. However if init takes on the WITH NAME form then autocomplete does not work. Also not it is possible to init with params.

*** Settings ***
Library        RobotLibIsBest     WITH NAME mylib

then 

in the *.robot file if i type

*** Test Cases ***
     mylib.(tab) ----> nothing happens however it is still recognizing keywords with out mylib. prefix. This causes an issue if i initialize two lib instances with different arguments and then i have no way to actually call either instance.

**Comment by jnhyperion** [comment]
will consider adding this feature in the future

**Comment by myjniak** [comment]
![hyper_rf_support2](https://github.com/jnhyperion/HyperRobotFrameworkPlugin/assets/39498464/9d7ea36d-3a48-47a2-a008-e1249c9649f2)

I'd love to see this happen!

Of course the actual use case for us is not OperatingSystem :D 

We have multiple libraries that give access to services.
They all have a keyword "Connect"
And some of them are submodules in a library.
So currently, we are more or less forced to do as follows:

```robot
*** Settings ***
Library    LibA.ModuleA.SubmoduleA
Library    LibA.ModuleA.SubmoduleB

*** Test Cases ***
Test1
    LibA.ModuleA.SubmoduleA.Connect
    LibA.ModuleA.SubmoduleB.Connect
``` 

But this would look a bit more elegant, and still intuitive:

```robot
*** Settings ***
Library    LibA.ModuleA.SubmoduleA    AS   SubmoduleA
Library    LibA.ModuleA.SubmoduleB    AS   SubmoduleB

*** Test Cases ***
Test1
    SubmoduleA.Connect
    SubmoduleB.Connect
``` 
(Note that there is more than just Connect, and we would have to flood Robot resources with 'LibA.ModuleA.SubmoduleX')

**Comment by jnhyperion** [comment]
The implementation of this feature in my mind would be a little complicated, perhaps I didn't find the correct solution. I'll figure it out when I have enough time :)

**Comment by Santherus** [comment]
Would like to add a vote to this one: Currently using the old Intellibot #patched  plugin (but would like to move to something like this great plugin), which offers autocomplete on CTRL+SPACE to complete a MyResource. with a list of the appropriate keywords.

Sadly not usable for us for now; I hope this feature makes it into the plugin in future!

**Comment by jnhyperion** [comment]
Supported in `0.1.17`.
