### ISSUE TITLE
Resource import in ***settings*** section causes code analysis warning on commit. IntelliJ 2022.1.1 with pycharm plug-in on Linux

### ISSUE THREAD

**Issue by alexshagiev** [jnhyperion/HyperRobotFrameworkPlugin#15]
Warn: Unused import statement

**Comment by alexshagiev** [comment]
![F92CE3EC-9BF6-4A3F-B96E-EBEDC31A233E](https://user-images.githubusercontent.com/24636886/188735170-b7778394-9d19-42a5-a590-435b8cb7637d.jpeg)

**Comment by jnhyperion** [comment]
I guess the keyword in your current robot file is not directly defined in the resource file you imported, is it defined in the other resource file but import in `main.resource`/`fixemulator.resouce`?

for now plugin will only consider the resource is used when the keyword directly defined in the resource file, no recursive search.

**Comment by alexshagiev** [comment]
Apologies but I am not following what is causing this still. My resource file Conley contains a library in ***settings*** section and the lib a python class with all imports in order

**Comment by jnhyperion** [comment]
added this feature in 0.0.8.

`Incorrect inspection warning when resource file is not directly used in transitive import`
