### ISSUE TITLE
multiline code block collapse/expand

### ISSUE THREAD

**Issue by alexshagiev** [jnhyperion/HyperRobotFrameworkPlugin#16]
the plugin provides a decent code collapse/expand capabilities on Sections & Tests but for not for multi line sections.  Example:

*** Test Cases *** # Collapsible
My Fav Test # Collapsible
   &{var}  = Create Dictionary # ======> Not Collapsible
   ... A=1
   ... B=2

'# blah blah blah  #  ===========> Not Collapsible - comment block
'# 123
'# xyz

**Comment by jnhyperion** [comment]
added multi-lines statement collapse feature in version 0.1.0

**Comment by jnhyperion** [comment]
added comments collapse feature in version 0.1.1
