### ISSUE TITLE
IF - END sequence break next keyword line above

### ISSUE THREAD

**Issue by ejandzej** [jnhyperion/HyperRobotFrameworkPlugin#18]
I noticed that keyword's navigation is not usable with a ctrl + mouse click when the previous keyword end with the "END" keyword. The example below is on the screen.
The code is working, but the syntax is broken, and the keyword is not well formatted in orange color. The first letter is white, the next are yellow. 

![if_end](https://user-images.githubusercontent.com/9215607/193019685-a414ff28-d07b-4374-87ec-425201ad61c1.png)

**Comment by jnhyperion** [comment]
this issue should be fixed in the latest version 0.0.9.
