### ISSUE TITLE
Navigation doesn't work when last keyword word is a variable

### ISSUE THREAD

**Issue by ejandzej** [jnhyperion/HyperRobotFrameworkPlugin#21]
When the last keyword word is a variable, navigation to the keyword's definition (ctrl + mouse click) doesn't work.
Example (doesn't work):
`Calibration step for ${color}`
![image](https://user-images.githubusercontent.com/9215607/194048263-08df0974-034d-4537-9ef9-afad794a2343.png)

But when I add some word at the end it works
Example (does work)
`Calibration step for ${color} foo`
![image](https://user-images.githubusercontent.com/9215607/194048349-f2fb697f-15e0-4029-a3c7-cf31715a5ff4.png)
This also works even when the keyword definition is "Calibration step for ${color}" (without foo at the end). But somehow the 'foo' enables us to navigate to this keyword. But when I place the mouse on the text before the `${color}` variable navigation still doesn't work, even with 'foo' at the end.

It looks like if there is no variable at the end navigation works fine. Still, with the variable at the end, navigation doesn't see this variable as part of the keyword, and navigation is broken.
But when a variable is in the middle of a keyword it again sees a keyword as correct (in the form of navigation)

**Comment by jnhyperion** [comment]
If your variable is static defined somewhere, we can try to search and get this value, this is doable in the future.

Or else your variable is dynamically passed from command line, the plugin will never know the value, the keyword navigation will be impossible.

**Comment by ejandzej** [comment]
In this situation, a variable will be defined when calling a keyword, e.g. `Calibration step for BLACK` / `Calibration step for YELLOW`, etc.

**Comment by jnhyperion** [comment]
I see, this should be a plugin bug of keyword style: "[Embedding arguments into keyword name](https://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#toc-entry-310)".

Thanks for reporting, will fix in next version.

**Comment by ejandzej** [comment]
Fingers crossed, and thank you that you are developing this plugin :)

**Comment by ejandzej** [comment]
Hi, any update on that? This still not working, even in version 0.1.0

**Comment by jnhyperion** [comment]
@ejandzej  sorry, I haven't got time to fix this bug in 0.1.0, maybe will fix in 0.1.1.

**Comment by jnhyperion** [comment]
@ejandzej I looked into this issue, found out there's no simple solution for it, because the navigation (keyword reference) actually works, but the the variable reference in the end is totally overlapped with the keyword, so when you click the keyword end, IDE does not know the variable or keyword you want to navigate.

there's a simple workaround for your case, just add a blank in your kw end, like this

```
"kw ${var} "
```
then when you press ctrl/cmd, you w'll see the underline in the blank, click it will navigate to the correct kw declaration.

**Comment by jnhyperion** [comment]
finally found a proper solution, and fixed in `0.1.1`.
