### ISSUE TITLE
Navigation not working

### ISSUE THREAD

**Issue by heunck** [jnhyperion/HyperRobotFrameworkPlugin#27]
Using PyCharm 2022.2.3 (Build #PC-222.4345.23) or IntelliJ IDEA 2022.2.3 (Build #IU-222.4345.14)
navigating to referenced files doesn't seem to work properly. 

We are importing Resources like the example below, which doesn't work.
*** Settings ***
Resource    ../../APIResources/RESTResourceCollector.resource

But if we remove the path prefixes and only reference the file, the navigation works (but our tests will fail because the location is not correct)
Resource    RESTResourceCollector.resource

Is this a bug or am I doing something wrong in my project setup ?

**Comment by jnhyperion** [comment]
perhaps related to https://github.com/jnhyperion/HyperRobotFrameworkPlugin/issues/20

**Comment by heunck** [comment]
Looks indeed the same.
