### ISSUE TITLE
PyCharm freezes often when navigating from another window back to PyCharm 

### ISSUE THREAD

**Issue by PhPstr** [jnhyperion/HyperRobotFrameworkPlugin#28]
After installing this plugin and without having any other plugins, PyCharm became to freeze for a few minutes after jumping from another window back to PyCharm. After freeze, everything works fine until next freeze. Issue doesn't happen every time but often. There isn't any related log available, at least none of the PyCharm logs did grow after or during freeze situation. 

My project is quite huge if that could somehow explain the situation. Without this plugin everything works fine.

Any ideas? Has anyone else reported this kind of behaviour?

=== About ===
Build version: PyCharm 2022.2.3 Build: #PC-222.4345.23 October 10, 2022
Theme: Darcula
JRE: 17.0.4.1+7-b469.62, JetBrains s.r.o.
JVM: 17.0.4.1+7-b469.62, OpenJDK 64-Bit Server VM, JetBrains s.r.o.
Operating System: Windows 10 10.0 (amd64)
idea.config.path=C:\..\JetBrains\PyCharmCE2022.2
idea.system.path=C:\..l\JetBrains\PyCharmCE2022.2
idea.plugins.path=C:\..\JetBrains\PyCharmCE2022.2\plugins
idea.log.path=C:\..\JetBrains\PyCharmCE2022.2\log
_JAVA_OPTIONS=-Xmx2G

=== System ===
Number of CPU: 4
Used memory: 397Mb 
Free memory: 997Mb 
Total memory: 1395Mb 
Maximum available memory: 2048Mb

=== Plugins ===
Custom plugins: [Hyper RobotFramework Support (0.1.2)]
Disabled plugins:[]

**Comment by jnhyperion** [comment]
hi, "jumping from another window" means you switch to other app, not pycharm then go back to pycharm right?
in that app, did you modify the any files in your project?

**Comment by jnhyperion** [comment]
in pycharm -> help -> diagnostic tools -> activity monitor, open this tool and try to reproduce this problem, then take a screenshot, it will show the heavy loading functions.

**Comment by PhPstr** [comment]
Yes, I mean exactly that I'm using some other app. And no, I'm not modifying the files. App can be any, just different than PyCharm. E.g. browser.

Unfortunately, it seems that also Activity Monitor freezes at the time when issue is seen. I can quite easily reproduce this issue. 

This is copy-paste at the moment when freeze eases but seems almost the same as idle process when just hovering around in PyCharm:

Right after freeze:
 %CPU  Subsystem

100,9  <Process total CPU usage>
 51,8  <JIT compiler>
  6,9  <unidentified: UI thread>
  5,4  <infrastructure: AWT-Windows>
  3,8  Plugin Shared Indexes: indexing.composite (in com.intellij)
  3,1  ui.components (in com.intellij)
  3,1  <Activity Monitor>
  3,1  ide.actions (in 
  
In the meantime, I'm using another plugin for Robot Framework and it works perfectly. It just lacks some of the nice methods your plugin has.

**Comment by jnhyperion** [comment]
what does your huge project look like?

- thousands lines of test case robot file
- thousands kw defined in resource file
- thousands kw defined in python file

I tried these scenarios, plugin runs with heavy load but no freeze happened.

can you help create a minimum demo to reproduce this problem?

**Comment by PhPstr** [comment]
It's a git repository with about thousand users. Here is some snips of the repo:
![image](https://user-images.githubusercontent.com/3593488/201922384-98687b85-7ded-4131-81f6-ed44664c0131.png)
![image](https://user-images.githubusercontent.com/3593488/201922570-c9cd6c48-facd-4729-ac2f-e8d4c03d0a22.png)

Still, everything works without this plugin. Anyway, since I'm not able to deliver any useful logs and no one else has seen this issue, I'll just disable this plugin and use intellibot for now.

I'm installing new computer atm. and I'll try this plugin also for it later.

**Comment by jnhyperion** [comment]
wow, such a huge project, are all the files robot files?

I assume tests with robot file are only part of them, such as a `tests` folder in under a huge project.

if so, just open `tests` folder instead of `root` folder.

**Comment by jnhyperion** [comment]
in `pycharm -> help -> show log in explorer` open the log folder and delete all logs and restart pycharm

then reproduce this problem, in the log folder there will be some logs like `threadDumps-freeze-20221116-100620-PC-222.4345.23-8sec`

can you help provide this logs?

**Comment by PhPstr** [comment]
There are some config-files and some text files but mostly robot tests and python libraries for robot. I can't separate the rate of the files. "A lot" is the word for robot and python files.

I tried earlier to provide threadDumps-freeze logs but there weren't coming any during or after the freeze. 
"There isn't any related log available, at least none of the PyCharm logs did grow after or during freeze situation."  - this sentence from the first message referred to those logs.

This time it seems that there are plenty of logs, I'm not sure which are relevant and which not. At least in last log file there was something of the hyper robot framework plugin as well. Please, take a look:

[threadDumps-freeze-20221116-095804-PC-222.4345.23.zip](https://github.com/jnhyperion/HyperRobotFrameworkPlugin/files/10019365/threadDumps-freeze-20221116-095804-PC-222.4345.23.zip)

**Comment by PhPstr** [comment]
Just tried with new computer and the same thing happens. So it's not about the computer or performance at least.

**Comment by jnhyperion** [comment]
@PhPstr thanks for your logs, I found the root cause, plugin is doing t0o much tasks in the UI threads instead of background threads. this will be fixed in `0.1.3`.

**Comment by jnhyperion** [comment]
@PhPstr dose version `0.1.3` resolve your problem?

**Comment by PhPstr** [comment]
Hi,

I haven't worked that much with this project lately but it seemed to work. At least no freezes were seen when I made last commits.
