### ISSUE TITLE
Import behavior for some Libraries differs from Vers. < 0.1.2

### ISSUE THREAD

**Issue by frodo23g** [jnhyperion/HyperRobotFrameworkPlugin#33]
Hello,
After the Fix for Relative Path on Windows Machines https://github.com/jnhyperion/HyperRobotFrameworkPlugin/issues/20 some Libraries that are used Imports Different then before. 

For Example: 
- robotframework-browser
- DateTime

For Both Libs the Import different. 
DateTime is a Standard Lib and before Ver. 0.1.2 it is Possible to use the Keywords from suggestion, when i import it under Settings as
`*** Settings ***`
`Library           robot.libraries.DateTime`

The Browser Lib, an external Library, I can use 
`*** Settings ***`
`Library           Browser`
And i can use the suggested Keywords.

After Vers. 0.1.2
DateTime Lib can now be imported normal
`*** Settings ***`
`Library           DateTime`
but for the Browser Lib I can't find another way to Import it, that I can use suggested Keywords.

Maybe it is a new Bug, that comes from the Change for the Fix of https://github.com/jnhyperion/HyperRobotFrameworkPlugin/issues/20

**Comment by jnhyperion** [comment]
confirmed, this is a bug.

**Comment by jnhyperion** [comment]
fixed in version `0.1.4`

**Comment by frodo23g** [comment]
As far as I can see, that fix is working and I can't find a Lib in my Project, where the Import doesn't deliver any Suggestions for Keywords. :-)
