### ISSUE TITLE
Plugin not work

### ISSUE THREAD

**Issue by kanchi240** [jnhyperion/HyperRobotFrameworkPlugin#34]
Hi, I installed from PyCharm market, but it seems the plugin is not working, there is no syntax hight and so on.

PyCharm version: PyCharm 2022.1.2 (Community Edition)
System: macOS Catalina
Python: 3.7.1
Robot: 4.0

**Comment by frodo23g** [comment]
Did you restart your IDE? Are you using a .robot File with the Robot Syntax?
I never used it with macOS, but on Windows and Linux it's working.

**Comment by jnhyperion** [comment]
Any errors shown in your `PyCharm` right bottom corner?

**Comment by kanchi240** [comment]
> Did you restart your IDE? Are you using a .robot File with the Robot Syntax? I never used it with macOS, but on Windows and Linux it's working.

Yes, file extension is .robot, and restart IDE after installed.

**Comment by kanchi240** [comment]
> Any errors shown in your `PyCharm` right bottom corner?

No errors display, by the way, is this plugin need to connect internet to use?

**Comment by jnhyperion** [comment]
@kanchi240 plugin does not need network.

You can try to uninstall other any robot related plugins, and reinstall `Hyper RobotFramework Support`.
