### ISSUE TITLE
How to specify global run options

### ISSUE THREAD

**Issue by kanchi240** [jnhyperion/HyperRobotFrameworkPlugin#38]
Hi,
My tests need to specify a lot of public run options, for example tests need to specify which environment will be used before running by adding a custom variable `-v env:uat`. It can be specified in every test run configuration, but is there a way to specify these public options in a global place? So these options will be specified only once.
Thanks.

**Comment by jnhyperion** [comment]
you can use the new feature in  version `0.1.4`:

* Standalone Robot run configuration, support configuration template

in your pycharm `Run/Debug Configurations` -> `Edit Configuration Templates...` select `Robot`

and add your global parameters there.

<img width="998" alt="image" src="https://user-images.githubusercontent.com/20297196/210912494-056e09f0-6480-4173-81bd-efb01942aff4.png">

remember to delete all existing run configurations, and directly run test from IDE, plugin will generate new run configuration form your template automatically.

**Comment by kanchi240** [comment]
@jnhyperion  Thanks!
