### ISSUE TITLE
Support multiple suites execution

### ISSUE THREAD

**Issue by kanchi240** [jnhyperion/HyperRobotFrameworkPlugin#39]
Hi,
I have a suite folder that contains some robot test suite files in it, can you support run all the tests in the folder?
Is there a way to execute all tests in `testsuite1.robot` and `testsuite2.robot` as below?

testsuites(folder)
        -- testsuite1.robot
        -- testsuite2.robot

Thanks!

**Comment by jnhyperion** [comment]
For now there's no execution button on the IDE support this.

You can use command line, or edit run arguments in the run configurations for alternative.

**Comment by kanchi240** [comment]
OK, thanks!
