### ISSUE TITLE
Add support for *** Tasks *** syntax

### ISSUE THREAD

**Issue by Taelyth** [jnhyperion/HyperRobotFrameworkPlugin#41]
The syntax for the *** Tasks *** is not working.
I'm using Robot Framework 4.1.3 and PyCharm Community Edition 2021.3.2.

![image](https://user-images.githubusercontent.com/88788491/155337913-05e8f90b-1fd7-40bc-a740-de36f0e76d9f.png)

Could you fix that, please?

**Comment by jnhyperion** [comment]
try to update to 2.0.
