### ISSUE TITLE
Variable definition not found

### ISSUE THREAD

**Issue by luki922** [jnhyperion/HyperRobotFrameworkPlugin#43]
Hey, @jnhyperion will you continue to develop this plugin?

**Comment by jnhyperion** [comment]
sure, any issues found?

**Comment by luki922** [comment]
I use PyCharm Professional 2022.3.2
Have issue with highlighting and error: "Variable definition not found":

![Snapshot_2023-02-09_13-31-25](https://user-images.githubusercontent.com/3541269/217813959-c4f64931-b401-45d3-805c-d81c095d10f5.png)


 All variables is loaded with:
`Variables       variables/XpathVariables.py` etc in `*** Settings ***` section:
![Snapshot_2023-02-09_13-44-47](https://user-images.githubusercontent.com/3541269/217816409-2ffe28ba-0638-435d-bc6e-bed77c16ec86.png)


> Example RegisterVariables.py:

    def get_variables():
    variables = {
        "Firstname ": "firstname",
        "Lastname": "lastname",
        "Email": email_generated,
        "Email generated": email_generated,
        "Password": "password",
        "Confirm password": "password",
    }
    return variables

Only `${EmailGenerated}` works because in variable file I have `email_generated = generate_email()`

**Comment by jnhyperion** [comment]
It's because your variables defined in `get_variables()` are only generated in robot runtime, IDE will never know it's return value.

for your example, yon can directly define the variable in python file:
```
Firstname = "firstname"
```

another solution is using python3 `dataclass`
```
from dataclasses import dataclass, asdict
@dataclass
class TestData:
     foo: str = "foo"

def get_variables()
    return asdict(TestData())
```

**Comment by luki922** [comment]
works thanks :)

**Comment by victor-varjo** [comment]
I know the issue is closed, but just wanted to check if there is any appetite to reopen it, since it's a design decision not to run the python file to get the variables. It is possible to do it (and [RobotCode](https://github.com/robotcodedev/robotcode), for example does it).
