### ISSUE TITLE
Issue with navigation using environment variable

### ISSUE THREAD

**Issue by ynamasse** [jnhyperion/HyperRobotFrameworkPlugin#45]
Hi,

When referencing a resource/variable/library, if i use an absolute/relative path (for example 
Library     ../../global_variables/simuInfos.py

Navigation is working well (we can navigate to file, also keywords from this file are known) and it is ok at runtime.

If i'm using an environment variable (set at computer or at pycharm level), the IDE does not recognize it (variable not found) so there is no navigation to file/keywords.
However, it is still working at runtime.

(issue similar to this in other robot framework : https://forum.robotframework.org/t/keywords-not-recognized/5041/6 )
https://github.com/robocorp/robotframework-lsp/issues/548 

Thanks

**Comment by jnhyperion** [comment]
As you described, this `missing variables` are `runtime/env variables`, plugin will never know the values, plugin will only static analyze your code to parse the variables.
