### ISSUE TITLE
[PyCharm] Import file not found

### ISSUE THREAD

**Issue by luki922** [jnhyperion/HyperRobotFrameworkPlugin#50]
After plugin update from 0.1.5 to 0.1.7 it doesn't recognize **Resource** imports.

Resource that contain keywords are imported correctly, only those with only Variables don't work. 

Resource file only with vartiables example:

```
*** Variables ***

${top_menu_login_xpath}                 //div[@class="top-menu-wrapper"]//a[contains(@href,"login")]
```

**Comment by jnhyperion** [comment]
thanks for your reporting, will be fixed in `0.1.8`
