### ISSUE TITLE
Support with .txt test case in Run Configuration

### ISSUE THREAD

**Issue by shaoerkuai** [jnhyperion/HyperRobotFrameworkPlugin#53]
Robot Framework's latest default support for.txt packages is no longer available, but it is still possible to enable the txt suite support of previous versions through the --extension robot:txt format,

 I noticed Hyper temporarily unable to support it (for TXT format binding for robot in pycharm file type, automatic completion works, Run Configuration not work unfortunately)
Suggest add the --extension parameter to the every new run configuration by default to enable support for the.txt suite of use cases (forward compatibility)
![image](https://github.com/jnhyperion/HyperRobotFrameworkPlugin/assets/117460332/31d9c789-632b-44c7-a782-65b953ac0779)
`--extension robot:txt --test "package.childpackage.case.`

**Comment by shaoerkuai** [comment]
Maybe add a option in Robot option panel?

**Comment by jnhyperion** [comment]
My suggestion is that to convert all your `.txt` file suffix to `.robot`, which is better for your tests readability.

If you still want to use `.txt`, you can:

- associate file type `txt` with plugin (this step you may have done, but I am not sure if there will be some other plugin errors when opening other raw txt files)
- in run configuration, click `edit configuration templates`, add additional parameters `--extension robot:txt` and apply, then all new created run configuration by clicking the run button will have this param
