### ISSUE TITLE
Import file not found.

### ISSUE THREAD

**Issue by CHIH-CHENG-TAI** [jnhyperion/HyperRobotFrameworkPlugin#55]
Hi,

Warning message "Import file not found." if I import python folder.

e.g.,
![image](https://github.com/jnhyperion/HyperRobotFrameworkPlugin/assets/27275948/fa19f259-041d-4dde-9649-2e6f0a61fb08)

![image](https://github.com/jnhyperion/HyperRobotFrameworkPlugin/assets/27275948/2e2c2ad2-7e4e-4ff6-b9b9-60249b504963)

**Comment by jnhyperion** [comment]
in your case, your library is a directory witch ide plugin is not supported, but looks like the kw can only be defined in `__init__.py` for this approach, so, your setting is equivalent to `Library    mylib/__init__.py`, you can use this as workaround


another workaround is to change your lib to a module:

``` python
# mylib/foo.py

class Foo:
    def kw(self):
         pass
```

and your setting should be `Library     mylib.foo.Foo`, note that this approach requires your lib is in the root folder of your project

**Comment by CHIH-CHENG-TAI** [comment]
Thanks for your sharing
