### ISSUE TITLE
Code Completion doesn't work when type Library

### ISSUE THREAD

**Issue by DANIKE** [jnhyperion/HyperRobotFrameworkPlugin#56]
*** Settings ***
Library    JSONLibrary
There is the problem when I type the "JSONLibrary", Although I hava installed the library.

**Comment by jnhyperion** [comment]
This is expected behaviour, because the robot library is actually a python library, in your system, there will be many python libraries, plugin will not know which library is robot library for now (except for the builtin libraries which are embedded in robotframework).

**Comment by jnhyperion** [comment]
Scanning all the python libraries to find out all possible robot libraries will be resource consuming, so I think it's not a good idea. Feel free to reopen this ticket.
