### ISSUE TITLE
Can't found the Library Selenium2Library's keywords' definition

### ISSUE THREAD

**Issue by DANIKE** [jnhyperion/HyperRobotFrameworkPlugin#57]
Hi, I new a robot file and add the Selenium2Library Library, but it shows 'keyword definition not found' when I move the mouse over "Click Element" , one of the keyword of Library Selenium2Library.
eg:
*** Settings ***
Library    Selenium2Library
*** Keywords ***
eg1
    Click Element    some_element

**Comment by jnhyperion** [comment]
Make sure you have installed latest `robotframework-selenium2library` in your current `pycharm` python interpreter.

**Comment by DANIKE** [comment]
I have installed robotframework-selenium2library 3.0.0, and it seems the latest version in https://pypi.org/.
My computer system is windows.
![image](https://github.com/jnhyperion/HyperRobotFrameworkPlugin/assets/7931772/46bcd89a-f5c6-4929-85d7-6cdba306546a)

**Comment by jnhyperion** [comment]
did you config your pycharm python interpreter well?

https://www.jetbrains.com/help/pycharm/configuring-python-interpreter.html#widget

and make sure your library is installed in the same python with your pycharm if you system has multi python

**Comment by DANIKE** [comment]
Yes, the config of pycharm python interpreter is right, and the keyword can run corectly. I just can't find the keyword defenition or use Code Completion.
But the robot's builtin librarys work well.

**Comment by jnhyperion** [comment]
I am not able to reproduce your problem.

<img width="548" alt="image" src="https://github.com/jnhyperion/HyperRobotFrameworkPlugin/assets/20297196/48eeac63-4e11-4699-a5f9-f7dd343f87fd">

try:

1. update plugin to latest version
2. close and reopen pycharm
3. according to the library intro "Starting from version 3.0, Selenium2Library is renamed to [SeleniumLibrary](https://github.com/robotframework/SeleniumLibrary) and this project exists mainly to help with transitioning.", using SeleniumLibrary instead

**Comment by jnhyperion** [comment]
Cannot reproduce, closed.

**Comment by DANIKE** [comment]
Hi, my robotframework-selenium2library's version is 3.0.0, robotframework-seleniumlibrary's version is 3.2.0，I have tried many times (including upgrade the plugin version and didn't work) and I found the  robotframework-seleniumlibrary's version did not have the problem. But our projects use 3.2.0 version for a long time  and there is some difference between the two  robotframework-seleniumlibrary version.
I really want to know the real reason, becase it runs well and it didn't have the problem when using ride.
I really like your plugin, so if there is someway to solve the problem, I will very thankful for it.

**Comment by jnhyperion** [comment]
Thanks for supporting my plugin.

First of all, you need to confirm if the library is correctly imported.

<img width="903" alt="image" src="https://github.com/jnhyperion/HyperRobotFrameworkPlugin/assets/20297196/d215bb79-2d9c-4eff-8889-09ff1a90e84d">

then plugin will search the kw definition in `pyi` file: `your_python_interpreter_lib_folder/site-packages/SeleniumLibrary/__init__.pyi`, you can check if this file can be found.

**Comment by DANIKE** [comment]
Thanks, the real reason is there no file:your_python_interpreter_lib_folder/site-packages/SeleniumLibrary/__init__.pyi. The problem dispeares when I put the file into the path. The __init__.pyi file starts from robotframework-seleniumlibrary-5.0.0. Because of this, the code_completion function will not work in old versions(<5.0.0).
I want to know would you fix this problem and there are must some teams using the old version like us.

**Comment by jnhyperion** [comment]
I see, `pyi` file aims to allow any ide plugin to know the functions definition of a python library, because some of the python libraries' functions is dynamically generated in python runtime, `SeleniumLibrary` is this type of library too.

Without this `pyi` file, plugin will never know the kw definitions, so, the only way is to upgrade your `SeleniumLibrary` > 5.0.0.
