### ISSUE TITLE
way for plugin to recognize env or explicitly specified variables

### ISSUE THREAD

**Issue by amrmhmohamed** [jnhyperion/HyperRobotFrameworkPlugin#6]
Just like we can specify environment variables when we setup a run configuration, I want to be able to either have variables picked up from os environment or from a dedicated text field in settings. I want to be able to set LOC=./here/ and be able to reference internal libraries like so:`Library  	    ${LOC}/my_python.py` and `Resource        ${LOC}/my_robot.robot`.

Right now the indexing doesn't fail but it highlights such lines as warnings and hovering over complains with "Import file not found".

I really appreciate you working on this, I am finding it useful.

**Comment by jnhyperion** [comment]
this looks impossible, because the value of the global variable is generated during the robot runtime, IDE will not know it before the execution.
