### ISSUE TITLE
Always insert 4 whitespace when typing Tab to be removed as this is controled with the code style in PyCharm

### ISSUE THREAD

**Issue by martinandovski-rldatix** [jnhyperion/HyperRobotFrameworkPlugin#60]
Hi there,

In the latest release there was implementation "Always insert 4 whitespace when typing Tab". This can be controlled in PyCharm by setting that in the Code Style section in the settings. We use tab to have better alignment in the keywords when we are using instead of using spaces. Tab is automatically adjustable.

I would like to propose this to be available for adjustment as per user desire, by the Code Style in PyCharm or in the Robot Options section as a checkbox.

Additionally as a improvement I would suggest the functionality to Capitalize Keywords to be limited to Library keywords not the ones that are written by the user or to provide option to choose.

![image](https://github.com/jnhyperion/HyperRobotFrameworkPlugin/assets/88083604/0efd5430-0380-463e-b9a3-7f828a2991d4)

**Comment by jnhyperion** [comment]
I tested this pycharm option with the following text:

`${var}=(TAB)Mykw(TAB)foo(TAB)bar`

without this update the result is:

`${var}= Mykw    foo bar`

which is not what I expected:
`${var}=    Mykw    foo    bar`

this feature mainly aims to solve this problem, this also follows the python's https://peps.python.org/pep-0008/.

"""
Specifies using 4 spaces for each level of indentation, which is the convention followed by the Python community. Mixing spaces and tabs or using tabs with different widths can lead to code readability and consistency issues.
"""

**Comment by martinandovski-rldatix** [comment]
Ok so 2 issues we have here while using the plugin. Noting is broken in the code, but the different visibility in our code.

First issue:
When starting a new line and pressing tab form the keyboard if leaves 4 spaces instead of Tab even the indentation is set to tabs.
Usually people press tab and space and make misalignment of the code. Additionally when entering new line from keywords it leaves tab character in the beginning, but if you press tab on a new line it starts with 4 spaces.
![image](https://github.com/jnhyperion/HyperRobotFrameworkPlugin/assets/88083604/205dc55e-e465-4590-9bef-da46f7d31bf2)

Second issue is when writing keywords and put tab to separate the xpath, Robot has the ability to distinct between 2 or more spaces and tab to separate keyword from arguments. Using spaces will be much harder to align then tabs. See example below.
![image](https://github.com/jnhyperion/HyperRobotFrameworkPlugin/assets/88083604/e3663792-8428-4131-adf3-bcedf5c26b9d)

When converting variables that is different and in the case above that you present if you have another variable beneath it which is called ${var1} you will get something like this
	${var}=            Mykw    foo    bar
	${var1}=          Mykw    foo    bar
	${variable}=    Mykw    foo    bar
And you will need to adjust the number of spaces to match the last row to make them in the same line, but using tabs
	${var}=		Mykw	foo	bar
	${var1}=		Mykw	foo	bar
	${variable}=	Mykw	foo	bar

I still believe this should be left on the user to be decided how they are going to use it. Additionally, on the case you have stated you can use 2 tabs to make it aligned.

**Comment by jnhyperion** [comment]
Make sense, will plan to add the option in next version so that you can disable this feature.

If this feature bothers you a lot, you can try to rollback to the previous version.

For the question about the capitalize kw name, you can try the option in

`preferences -> languages & frameworks -> Robot Options -> Capitalize Keywords`

**Comment by jnhyperion** [comment]
supported in `0.1.14`
