### ISSUE TITLE
Allow attach customize robot running commands

### ISSUE THREAD

**Issue by shaoerkuai** [jnhyperion/HyperRobotFrameworkPlugin#61]
还是我之前提过一个被closed的issue相关联的问题，希望提供一个选项能解析txt格式的用例

转念一想，txt格式本身就是新版Robot所舍弃的格式，所以没有必要单独提供一个选项，我这边通过修改txt用正则关联格式，依然可以用代码提示和高亮

但是，却因此挖掘出一个需求，当前直接执行用例的方式是：
--test  "XXX.XXX.." .
**希望能提供一个全局选项，支持定义每次执行用例时，加入自定义robot参数（参数可以在Robot Option提供一个文本框，用户自己去填写，分成suite 、case两种不同的自定义参数添加）**

比如说--loglevel debug 启用debug打印

这样我之前的需求，通过自定义参数，新增extension也能一起满足了~

**Comment by jnhyperion** [comment]
你说的这个”全局选项“听起来好像就是`configuration tamplate`。

对于通过plugin run button自动创建的run configuration，plugin会自动在robot命令行里加入“--test/--suite ...”，并把template里配置的额外参数append到命令行中。

对于你的例子，你可以在`configuration tamplate`里的`script parameters`里加入`--loglevel debug --extension robot:txt`。

**Comment by shaoerkuai** [comment]
试了下确实可以，先关闭，后面我针对这个提一个文档pr吧
