### ISSUE TITLE
Tab lengths are not dynamic for multiline alignment

### ISSUE THREAD

**Issue by QAthulhu** [jnhyperion/HyperRobotFrameworkPlugin#66]
Pressing Tab results in a strict tab length no matter what. Other plugins allow dynamic tab length to help align keywords
Ex.
```
Keyword One    ArgumentOne
Keyword Two    ArgumentOne
Keyword Three    ArgumentOne
Keyword Four    ArgumentOne
```

Because the keywords are different lengths, pressing tab results in misaligned arguments. When pressing tab a second time
```
Keyword One        ArgumentOne
Keyword Two        ArgumentOne
Keyword Three        ArgumentOne
Keyword Four        ArgumentOne
```

The same number of spaces are used for the tab. It would be better if the length of the tab was changed dynamically to align the arguments such that the second tab would result in this
```
Keyword One       ArgumentOne
Keyword Two       ArgumentOne
Keyword Three     ArgumentOne
Keyword Four      ArgumentOne
```

**Comment by jnhyperion** [comment]
you can disable this feature in preferences:

<img width="887" alt="image" src="https://github.com/jnhyperion/HyperRobotFrameworkPlugin/assets/20297196/2146d51a-5d2e-4a38-94c9-e4a28772aa43">
if it's disabled, the tab function should work the same with other file types, which can be configured here:
<img width="682" alt="image" src="https://github.com/jnhyperion/HyperRobotFrameworkPlugin/assets/20297196/9f8f5f9e-27fc-4896-b731-08bc5d257980">

**Comment by QAthulhu** [comment]
Ahh I see, thanks!
