### ISSUE TITLE
Debug run - when running test in debug mode PyCharm is not stopping in debug breakpoints inside the python code 

### ISSUE THREAD

**Issue by bwomsm1** [jnhyperion/HyperRobotFrameworkPlugin#68]
When we are running in debug mode:
<img width="434" alt="Screenshot 2024-04-03 at 12 34 58" src="https://github.com/jnhyperion/HyperRobotFrameworkPlugin/assets/5571230/4a30a97b-1869-4a8e-b871-0d67bdb1f103">

And setting a break point inside the python code:
<img width="373" alt="Screenshot 2024-04-03 at 12 36 45" src="https://github.com/jnhyperion/HyperRobotFrameworkPlugin/assets/5571230/a907df1c-5f33-4594-96aa-852a11c564aa">

Pycharm is not stopping the run in the break point, in our example, its line 447

**Comment by bwomsm1** [comment]
@jnhyperion can you please help with that issue? thank you

**Comment by jnhyperion** [comment]
Please check another break point and ensure the program will step into.

Or is your break point running in a sub process?
