### ISSUE TITLE
Cannot seem to generate new reports

### ISSUE THREAD

**Issue by abeward** [jnhyperion/HyperRobotFrameworkPlugin#70]
**My Setup:**
I have the published plugin version 0.1.16 installed via the Pycharm Marketplace. I'm working on automation with RobotFramework using SeleniumLibrary. I'm on a Mac M1 with the latest updates. I have updated all of my interpreter packages, and have the latest brew upgrades. Pycharm is up to date. Chrome is up to date. No warnings or errors when executing the test.

**My Issue:**
- Unable to generate reports for test runs executed with the Hyper tool.

**Here's what I've tried:**

- This could certainly be user error. I've tried to find a way to change how the tool behaves, so that it will generate reports via: google searches, the readMe, the tool settings, and I also tried a debugger run just in case it's programmed with a different function for reports than the standard run. I had no luck with any of these methods. 
- No issues generating a report when I was using IntelliBot and the manual terminal command, so I'm wondering if this tool simply doesn't support --report, or if there is a defect, or if I'm overlooking some configuration to enable it?

**Here are my repro steps:**

**Given** I run a test (I click the 'Play' icon next to the test in the .robot file that contains the test)
   **And** a test fails or passes
**When** I refresh the report.html browser tab that's already open
**Then** I still see an old report from 20240417
**When** I close and reopen the report.html
**Then** I still see the old report

My test runs with Chrome.

**Supplemental Information from RF website:**

> Run tests and generate reports
> To run your tests and generate reports, you can use the robot command with the --report and --log options. For example: robot --report report.html --log log.html tests This will create a report.html file that summarizes the test results and a log.html file that contains the detailed test execution information. You can also use the --output option to specify the name of the XML output file, which is needed for further processing.

**Request:**

Can you update the readMe to tell me how to ensure HyperRobotFrameworkPlugin generates a report for every run, or if there's a bug, would you be willing to fix it? The reporting capability is important to me. Thanks!

**Comment by jnhyperion** [comment]
The plugin does not generate the report, when you click the plugin `run` button, it will only run the corresponding
 robot commandline. By default, you shall see the robot output in the end of the run console, like this:

```
Output:  /example/output.xml
Log:     /example/log.html
Report:  /example/report.html
```

Please check if you're opening the correct `report.html`.

**Comment by abeward** [comment]
Please check if you're opening the correct report.html.

Ah, yes, I see now! User error, as expected. I didn't anticipate that the report might go into a different directory (and really ought to have). That was it. Thank you very much!

**Comment by abeward** [comment]
> Please check if you're opening the correct report.html.

Ah, yes, I see now! User error, as expected. I didn't anticipate that the report might go into a different directory (and really ought to have). That was it. Thank you very much!
