### ISSUE TITLE
Plugin does not recognize keywords for my project

### ISSUE THREAD

**Issue by restagner** [jnhyperion/HyperRobotFrameworkPlugin#72]
In my project, the plugin does not recognize the keywords listed within the Test Cases section.  However, if I open a _separate_ Robot Framework project the plugin works just fine.  It seems to a project-specific problem and I can't seem to figure out why that is the case

PyCharm: 2023.3.5 Community Edition
Pyenv: 2.3.36
Python: 3.11.1
Poetry: 1.8.2

I use Poetry to manage and run the project's test cases.

**Comment by jnhyperion** [comment]
please check the python interpreter settings (settings -> project -> python interpreter) of your project. Ensure the project python interpreter points to your correct `poetry` env, or just create new one:

<img width="785" alt="image" src="https://github.com/jnhyperion/HyperRobotFrameworkPlugin/assets/20297196/f17dc6a5-646f-477f-a7fb-336e3f40d7d9">
and activate it:

<img width="338" alt="image" src="https://github.com/jnhyperion/HyperRobotFrameworkPlugin/assets/20297196/d82c4c08-24af-4b9a-a28e-055793e20194">
