### ISSUE TITLE
Add support for VAR syntax (framework 7)

### ISSUE THREAD

**Issue by Santherus** [jnhyperion/HyperRobotFrameworkPlugin#73]
The [var syntax](https://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#var-syntax) added in Robot Framework 7 would be a great addition to the plugin.

Currently, attempting to use that syntax reports keyword definition not found... would be really nice to see this supported.

**Comment by Santherus** [comment]
Togther with a fix for https://github.com/jnhyperion/HyperRobotFrameworkPlugin/issues/14, this would probably make your plugin the primary 'standard' for robot.

**Comment by sd-yazzoom** [comment]
🎆 @jnhyperion! Thanks for adding the support for VAR. While I was able to update to the latest version in PyCharm, I do not see the code changes on github? Could it be that the code was not pushed to github or did I look in the wrong place?

**Comment by jnhyperion** [comment]
I just found some code conflicts from my local to remote, I gave up pushing due to my limited time, I'll update remote when I have enough time :)
