### ISSUE TITLE
Code Completion is not working on Pycharm 2024.1.1

### ISSUE THREAD

**Issue by danielyoga** [jnhyperion/HyperRobotFrameworkPlugin#74]
![Screenshot from 2024-05-16 17-02-04](https://github.com/jnhyperion/HyperRobotFrameworkPlugin/assets/55596578/7f804070-8ec3-4046-a162-731cb22f1112)

**Comment by jnhyperion** [comment]
please provide more details, from your screenshot, I cannot see any code completion issue.

**Comment by danielyoga** [comment]
![Screenshot from 2024-05-17 16-15-25](https://github.com/jnhyperion/HyperRobotFrameworkPlugin/assets/55596578/95cd16e0-8263-4d7a-bd22-8f943fd069bf)
on vs code i can use robot extension so it will do code completion like this. it doesnt work in pycharm

**Comment by danielyoga** [comment]
i'm expecting robot frameworks syntax on code completion

**Comment by jnhyperion** [comment]
<img width="650" alt="image" src="https://github.com/jnhyperion/HyperRobotFrameworkPlugin/assets/20297196/6766fd89-79d5-46d8-aadc-f6da638539aa">

I assume you're using library `rpaframework`, it works well in my local.

Please ensure your python interpreter is configured well for your pycharm, and the library is installed in that python env.

If the problem still exists, please provide a minimal project which can reproduce this problem.

**Comment by danielyoga** [comment]
![image](https://github.com/jnhyperion/HyperRobotFrameworkPlugin/assets/55596578/1c718c91-c802-4416-9f9a-8046681cb0fd)
is there any correlation with pycharm version? maybe it dont works with latest pycharm version? or maybe you can make a tutorial video to explain it? do you mind if we meet on gmeet/zoom?

**Comment by jnhyperion** [comment]
<img width="625" alt="image" src="https://github.com/jnhyperion/HyperRobotFrameworkPlugin/assets/20297196/6b8bd356-90a9-4abe-979f-246bed547087">
from your screenshot, it shows no library installed in your python env, you need to installed the dependencies in the env, for example: `pip install rpaframework`
