### ISSUE TITLE
Feature Request: resolve robot.api.deco keywords 

### ISSUE THREAD

**Issue by e2m32** [jnhyperion/HyperRobotFrameworkPlugin#76]
Robot Framework has the feature to create keywords as decorators to functions. 
https://robot-framework.readthedocs.io/en/latest/autodoc/robot.api.html#robot.api.deco.keyword

These keywords are not resolved by the Plugin. 
![image](https://github.com/jnhyperion/HyperRobotFrameworkPlugin/assets/10486510/7499ddf2-6037-4228-bb5f-a8902313085c)

Great plugin! Thank you for your work! Best one for PyCharm, I've tried them all.

**Comment by jnhyperion** [comment]
Thanks for your support.

<img width="659" alt="image" src="https://github.com/jnhyperion/HyperRobotFrameworkPlugin/assets/20297196/b79b7eab-ce2d-4eab-8f16-dd9e50e518e1">
<img width="694" alt="image" src="https://github.com/jnhyperion/HyperRobotFrameworkPlugin/assets/20297196/5e093110-bd46-4d98-a47b-7e388cba7e3d">

the keywords with the robot deco and custom name is supported, please provide more details.

**Comment by e2m32** [comment]
Ahh, ok perfect. Thank you for the explanation. The decorator I was using was formatted like this:

``` python
from robot.api import deco

@deco.keyword("custom name")
def example():
   pass
```

After updating to your import, it resolves. Thanks!
