### ISSUE TITLE
Add support for dynamic libraries

### ISSUE THREAD

**Issue by jasle** [jnhyperion/HyperRobotFrameworkPlugin#77]
I try to use the plugin with a [dynamic library](https://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#dynamic-library-api), but the keywords are not recognized.

Adding support for dynamic libraries to the plugin would be really great!

**Comment by jasle** [comment]
The interface for a dynamic library is also available as abstract base class in the robot api: https://github.com/robotframework/robotframework/blob/master/src/robot/api/interfaces.py#L91

**Comment by jnhyperion** [comment]
duplicated with: https://github.com/jnhyperion/HyperRobotFrameworkPlugin/issues/67

**Comment by jasle** [comment]
This is a bit different from the selenium library: There a no keywords as methods in my library, just the `get_keyword_names`, `run_keyword` method and so on.
I can generate docs with `libdoc`, but creating a .pyi file from it would be hard.

How does the plugin collect the information about robot libraries?

**Comment by jnhyperion** [comment]
Plugin will search the python class/file with the library name like: `SeleniumLibrary` (the library name in your import statement), then parse the keywords under it. For the dynamic library, the keyword is not defined under the class, the keywords are registered in the robot runtime. So that plugin will never know what're the keywords.

**Comment by jasle** [comment]
So there is no way to call the methods of the class to get the keywords and so on, right?

Is adding support for Libdoc XML or JSON spec files an option? This would allow to get the keywords with more information than it is possible with an `.pyi`-file, like source file and line, if implemented by the dynamic library.

**Comment by jnhyperion** [comment]
That's right, because plugin will not "execute" the python file, it just statically analyzes the python syntax. The [pyi file](https://typing.readthedocs.io/en/latest/source/stubs.html) is designed to resolve this kind of problem, so the other kind of stub file is not applicable.
