### ISSUE TITLE
assign top test suite folder to run/debug case

### ISSUE THREAD

**Issue by mfo7mfo7mfo7** [jnhyperion/HyperRobotFrameworkPlugin#85]
Could we assign top test suite path instead of hard-coded assigned .robot file while clicking run/debug button.
Since we have init.robot at top of test suites folder, `--test "xxx" /path/to/robot/xxx.robot` won't take any effect from top init.robot.

## [Suggestion]
* provide custom added path: /path/to/testcase-top-test-suite-folder/ 
    * suite run/debug: -s "{SUITE_NAME}" {TOP_TEST_SUITE_FOLDER} 
    * case run/debug: -t "{CASE_NAME}" {TOP_TEST_SUITE_FOLDER}

#### Test suite folder structure  
>|-- TopTestSuite  
>>    |-- init.robot                  # Initialization file for the top-level test suite  
>>    |-- SubSuite_1                  # First sub-suite, contains its own tests  
>>>        |-- init.robot              # Initialization file for SubSuite_1  
>>>        |-- TestSuite_1.robot       # Test cases for SubSuite_1  
>>    |-- SubSuite_2                  # Second sub-suite, contains its own tests  
>>>        |-- init.robot              # Initialization file for SubSuite_2  
>>>        |-- TestSuite_2.robot       # Test cases for SubSuite_2  

#### Scenario
* run TestSuite_1 test suite
    * robot -s "TestSuite_1" ./TopTestSuite 

* Assume there is a case called test_case_2 in TestSuite_2.robot, run test_case_2
    * robot -t "test_case_2 " ./TopTestSuite

---

Thanks. Nice work!!!!

**Comment by jnhyperion** [comment]
I didn't quite got your point, I tried in my local:
* my folder structure
```
root
├── test
│   ├── __init__.robot
│   └── sub
│       ├── __init__.robot
│       └── sub
│           ├── __init__.robot
│           └── test.robot
├── __init__.robot

```
* in `__init__.robot`:

``` root
*** Settings ***
Suite Setup    Log To Console    {folder name} based on it's location
```
* run test.robot via plugin's run button, command line auto generated:

```
python -m robot.run --suite root.test.sub.sub.test .
```
* output:
```
==============================================================================
Root                                                              
==============================================================================
***root folder***
Root.Test                                                         
==============================================================================
***test folder***
Root.Test.Sub                                                     
==============================================================================
***sub folder***
Root.Test.Sub.Sub                                                 
==============================================================================
***sub sub folder***
Root.Test.Sub.Sub.Test                                            
==============================================================================
example                                                              
| PASS |
```
* from the robot console, we can see the `__init__.robot` works well.

What's your pycharm project root workspace? the auto generated commandline will alway run under your project root dir.

**Comment by mfo7mfo7mfo7** [comment]
Hi @jnhyperion  Thanks for your prompt reply. I'm so thrilled that you try to reproduce for me. 

I'm using in Windows10 with poetry python interpreter and give project root folder as default "Working Directory" in running configurations, somehow, sometimes it would auto generated like this:

> C:\\path\to\poetry\python.exe -m robot.run --test test_case_2 C:/path/to/sub/sub/test.robot 
>>  it's not typo, i don't know why it's with "/" for robot file path C:/path/to/sub/sub/test.robot

---
 
Well, it works perfect while i remove default "Working Directory" and leave it blank. 

Thank you @jnhyperion
