### ISSUE TITLE
Navigation with left mouse click + CTRL doesn't work in version 0.0.6

### ISSUE THREAD

**Issue by ejandzej** [jnhyperion/HyperRobotFrameworkPlugin#9]
Hi,
After upgrading to version 0.0.6 keyword navigation doesn't work. Before I was able to click keyword with CTRL and navigate to its implementation - now it doesn't work. I have information "No usages in All Places". With version 0.0.5 it works fine.

![image](https://user-images.githubusercontent.com/9215607/185599485-9548015a-8fe6-4b34-b04c-0c45d17bd18a.png)

My environment:
Windows 10
Python 3.10.2
PyCharm 2021.3.3 Community Edition (I can't update because I have some other plugin that won't work with the newest version (Robot Framework Support))

**Comment by jnhyperion** [comment]
are there any plugin errors shown in the right bottom corner of PyCharm? Otherwise try to restart IDE.

And I noticed that you're using the `resource` file name prefix to invoke the keyword, is it because you have multi same name keywords in different `resource` files? if not, the prefix is not necessary. Perhaps the resource file prefix cause this issue.

**Comment by luismsilva99** [comment]
Hi all,
I got the same issue but to be honest I was never able to get the CTRL (CMD in my case) + click working. I have no IDE errors, just the same message as the opening post of this issue, "No usages found in All Places". Let me know if you have a tip, also happy to help on debugging if you think I can help @jnhyperion .

**Comment by jnhyperion** [comment]
@luismsilva99 can you provide a minimal example of your project?

like this:

<img width="372" alt="image" src="https://user-images.githubusercontent.com/20297196/186311876-0f5564c1-1c44-401b-9f64-d9db5a65506d.png">

every kw in my example can be linked to the correct position.

BTW, you need to set your python interpreter properly for your PyCharm

**Comment by luismsilva99** [comment]
Hi @jnhyperion ,

Thanks for your answer. I can jump to a keyword if it is declared in same file. What doesn't work is jump to keywords declared on other (resource) files.
I think my interperter is well defined. Should I also configure something specific on Project Structure?

Here's the requested screenshot.
![image](https://user-images.githubusercontent.com/5888092/186378167-f03b7a3d-f950-4669-a117-9efa070ef0d8.png)

**Comment by ejandzej** [comment]
Hi guys,
I made a test. I installed the newest PyCharm 2022.2.1 (Community Edition) and HyperRobotFramework Support in version 0.0.6 (newest). I disabled other plugins connected with Robot.

![image](https://user-images.githubusercontent.com/9215607/186451795-c1634ee2-522f-48c3-b559-b9c824e56942.png)

With this setup I have the same situation as @luismsilva99 - navigation with keywords works with keywords declared in the same file but it doesn't work for keywords imported from other files.
There is no plugin error.
I noticed that now Library and Resources files are marked in grey with the info "Import file not found ". Maybe here is the problem? In the previous version of the plugin, it wasn't like that.
![image](https://user-images.githubusercontent.com/9215607/186450889-11345035-6019-43b5-8555-a95e7b5cde38.png)

**Comment by jnhyperion** [comment]
@luismsilva99 your resource file path contains dynamic variable which plugin will never know the value, so the plugin cannot resolve your resource file, therefore all your kw are not recognized.

You can try replace your dynamic variable to fixed path value, and update your project structure design, this will also make your project more readable.

**Comment by jnhyperion** [comment]
@ejandzej does  left mouse click + CTRL work for your library and resource import?

the resource and library file path should be the relative path to your current robot file's dir.

**Comment by ejandzej** [comment]
> @ejandzej does left mouse click + CTRL work for your library and resource import?

@jnhyperion no it doesn't work. But in version 0.0.5 it was.

> the resource and library file path should be the relative path to your current robot file's dir.

In my robot-arguments.txt file, I have a pythonpath declared, as:
```
# Define where to look for additional resources
--pythonpath resources/ 
```
and in version 0.0.5 of the plugin, I always write a path to a libraries from `resources`. For example if I have a library in `resources/apps/cc_app_workflow.resource` in the .robot file I write `Resource  apps/cc_app_workflow.resource` and in version 0.0.5 it works fine and navigation with mouse and ctrl worked fine. In version 0.0.6 it stopped working

Example for 0.0.5 version. As you can see my `foo-tests/tests/xxx_Workflow/Automated_tests/New_Output_XXX/new_output_xxx.robot` is using files from `foo-tests/resources/workflow/` and it works. I just need to write `Resource  workflow/simulators_workflow.resource`, navigation in this example work. But after upgrading to 0.0.6 it's broken and stopped working. Any idea why?
![image](https://user-images.githubusercontent.com/9215607/186616343-f63429a2-6124-4ec0-b534-bb4017941fa2.png)

**Comment by jnhyperion** [comment]
@ejandzej find the root cause, in 0.0.5 if resource file is not recognized from it's relevant path, plugin will search this resource file name in entire project and return possible file path. this will cause incorrect resource file found when there're multi resource files with the same name.

since you have a pre-defined global variable `--pythonpath resources/` which also means your resource file path is dynamic and plugin will never know the exact path you want. My suggestion is to make your resource file path `fixed`, because if we still keep the behaviors of version 0.0.5 you may get unexpected resource file reference.

**Comment by ejandzej** [comment]
@jnhyperion it looks like with version 0.0.7 it works as in version 0.0.5 so the problem is fixed I think. I will continue to test that, but for now, in version 0.0.7 dynamics resource file paths work well, kudos to you :)
